"use client";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import Link from "next/link";
import {api,Lead} from "@/lib/api";
import {PageHeader,Score} from "@/components/dashboard-ui";
import {initials} from "@/lib/utils";
const stages=['New Lead','Qualified','Contacted','Meeting Scheduled','Proposal','Won','Lost'];
export default function Pipeline(){const qc=useQueryClient();const {data=[]}=useQuery({queryKey:['leads','pipeline'],queryFn:()=>api<Lead[]>('/api/leads'),refetchInterval:5000});const move=useMutation({mutationFn:({id,stage}:{id:string,stage:string})=>api(`/api/leads/${id}/stage`,{method:'PATCH',body:JSON.stringify({stage})}),onSuccess:()=>qc.invalidateQueries({queryKey:['leads','pipeline']})});return <><PageHeader eyebrow="CRM" title="Sales pipeline" description="Move opportunities as the buying conversation progresses."/><div className="flex gap-4 overflow-x-auto pb-6">{stages.map(stage=><section key={stage} className="w-72 shrink-0"><div className="mb-3 flex items-center justify-between"><h2 className="text-xs font-bold uppercase tracking-wider text-[#616b67]">{stage}</h2><span className="rounded bg-[#e9ece9] px-2 py-0.5 text-[10px] font-bold">{data.filter(l=>l.stage===stage).length}</span></div><div className="space-y-3 rounded-lg bg-[#ecefec] p-2 min-h-[420px]">{data.filter(l=>l.stage===stage).map(l=><article draggable onDragEnd={()=>{}} key={l.id} className="panel p-4 shadow-sm"><Link href={`/dashboard/leads/${l.id}`}><div className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-full bg-[#e9f0ec] text-[9px] font-bold">{initials(l.full_name)}</div><div><div className="text-xs font-bold">{l.full_name}</div><div className="text-[10px] text-[#7a837f]">{l.company}</div></div></div><div className="mt-4 flex justify-between"><Score score={l.score} classification={l.classification}/><span className="text-[10px] text-[#7d8582]">${Number(l.estimated_value).toLocaleString()}</span></div></Link><select aria-label={`Move ${l.full_name}`} className="field mt-3 h-8! text-xs" value={l.stage} onChange={e=>move.mutate({id:l.id,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></article>)}</div></section>)}</div></>}

