"use client";
import {useQuery} from "@tanstack/react-query";
import {Activity,CheckCircle2,Clock3,GitBranch,PlayCircle} from "lucide-react";
import {api} from "@/lib/api";
import {PageHeader} from "@/components/dashboard-ui";
type Automation={name:string;trigger:string;status:string;runs:number;success_rate:number|null;last_execution:string|null};
const purposes:Record<string,string>={"New Lead Qualification":"Scores and summarizes every inbound opportunity.","Hot Lead Follow-Up":"Sends a priority response with a booking CTA.","Warm Lead Nurture":"Starts a considered follow-up sequence.","Appointment Confirmation":"Confirms a booking and updates the lead timeline.","No Booking Follow-Up":"Re-engages interested leads who did not schedule.","Post-Meeting Follow-Up":"Keeps momentum after the first conversation."};
export default function Automations(){const {data=[]}=useQuery({queryKey:['automations'],queryFn:()=>api<Automation[]>('/api/automations'),refetchInterval:8000});return <><PageHeader eyebrow="Orchestration" title="Automations" description="An operational view of the n8n workflows behind your sales process."/><div className="grid gap-4 lg:grid-cols-2">{data.map(a=><article key={a.name} className="panel p-5"><div className="flex items-start justify-between gap-3"><div className="grid h-9 w-9 place-items-center rounded-md bg-[#e9f1ed] text-[#236450]"><GitBranch size={17}/></div><span className="pill bg-[#e5f2eb] text-[#236450]"><span className="h-1.5 w-1.5 rounded-full bg-[#318161]"/>Active</span></div><h2 className="mt-5 font-bold">{a.name}</h2><p className="mt-2 text-sm leading-6 text-[#68716d]">{purposes[a.name]}</p><div className="mt-5 grid grid-cols-3 border-t border-[#eceeec] pt-4"><Stat icon={<PlayCircle/>} label="Runs" value={a.runs}/><Stat icon={<CheckCircle2/>} label="Success" value={a.success_rate===null?'—':`${a.success_rate}%`}/><Stat icon={<Clock3/>} label="Last run" value={a.last_execution?new Date(a.last_execution).toLocaleDateString():'Not yet'}/></div><div className="mt-4 rounded-md bg-[#f5f6f4] px-3 py-2 text-[11px] text-[#717a76]"><b className="text-[#4f5955]">Trigger:</b> {a.trigger}</div></article>)}</div></>}
function Stat({icon,label,value}:{icon:React.ReactNode,label:string,value:string|number}){return <div className="border-r border-[#eceeec] px-3 first:pl-0 last:border-0"><div className="flex items-center gap-1 text-[10px] text-[#818985] [&_svg]:h-3 [&_svg]:w-3">{icon}{label}</div><div className="mt-1 text-xs font-bold">{value}</div></div>}

