"use client";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {Activity,BarChart3,Bot,CalendarDays,Inbox,Kanban,LayoutDashboard,LogOut,Menu,Settings,Users,X} from "lucide-react";
import {useEffect,useState} from "react";
import {Logo} from "./marketing";
const nav=[['/dashboard',LayoutDashboard,'Overview'],['/dashboard/leads',Users,'Leads'],['/dashboard/pipeline',Kanban,'Pipeline'],['/dashboard/automations,BAD',Bot,'Automations'],['/dashboard/appointments',CalendarDays,'Appointments'],['/dashboard/conversations',Inbox,'Conversations'],['/dashboard/analytics',BarChart3,'Analytics'],['/dashboard/settings',Settings,'Settings']] as const;
export default function DashboardShell({children}:{children:React.ReactNode}){const path=usePathname(),router=useRouter();const [open,setOpen]=useState(false);useEffect(()=>{if(!localStorage.getItem('sf_token'))router.replace('/login')},[router]);function logout(){localStorage.removeItem('sf_token');router.replace('/login')}return <div className="min-h-screen bg-[#f6f7f5]"><button aria-label="Open navigation" className="fixed left-4 top-4 z-50 rounded-md bg-white p-2 shadow md:hidden" onClick={()=>setOpen(true)}><Menu size={19}/></button><aside className={`fixed inset-y-0 left-0 z-50 flex w-60 flex-col border-r border-[#e3e6e3] bg-white p-4 transition-transform md:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex h-10 items-center justify-between px-2"><Logo/><button className="md:hidden" onClick={()=>setOpen(false)}><X size={18}/></button></div><nav className="mt-7 space-y-1">{nav.map(([href,Icon,label])=>{const url=href.replace(',BAD','');const active=url==='/dashboard'?path===url:path.startsWith(url);return <Link onClick={()=>setOpen(false)} key={url} href={url} className={`flex h-9 items-center gap-3 rounded-md px-3 text-sm ${active?'bg-[#edf3f0] font-bold text-[#1e5946]':'text-[#626c68] hover:bg-[#f4f5f4]'}`}><Icon size={16}/>{label}</Link>})}</nav><div className="mt-auto border-t border-[#eceeec] pt-4"><div className="flex items-center gap-3 px-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#e1eee8] text-xs font-bold text-[#236450]">DA</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">Demo Administrator</div><div className="text-[10px] text-[#808985]">Workspace owner</div></div><button onClick={logout} aria-label="Log out" className="text-[#7a837f] hover:text-[#1a1d1b]"><LogOut size={16}/></button></div></div></aside><main className="md:pl-60"><div className="mx-auto min-h-screen max-w-[1440px] px-5 py-6 md:px-8 md:py-8">{children}</div></main></div>}

