"""initial salesflow schema"""
from alembic import op
import sqlalchemy as sa
revision="20260911_0001"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    stage=sa.Enum('NEW','QUALIFIED','CONTACTED','MEETING','PROPOSAL','WON','LOST',name='stage')
    temperature=sa.Enum('COLD','WARM','HOT',name='temperature')
    runstatus=sa.Enum('PENDING','RUNNING','SUCCEEDED','FAILED',name='runstatus')
    op.create_table('users',sa.Column('id',sa.String(36),primary_key=True),sa.Column('email',sa.String(320),nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('name',sa.String(120),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('email'))
    op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_table('leads',sa.Column('id',sa.String(36),primary_key=True),sa.Column('full_name',sa.String(160),nullable=False),sa.Column('email',sa.String(320),nullable=False),sa.Column('company',sa.String(180),nullable=False),sa.Column('job_title',sa.String(160),nullable=False),sa.Column('company_size',sa.String(80),nullable=False),sa.Column('industry',sa.String(120),nullable=False),sa.Column('interest',sa.Text(),nullable=False),sa.Column('budget',sa.String(80),nullable=False),sa.Column('timeline',sa.String(80),nullable=False),sa.Column('message',sa.Text()),sa.Column('source',sa.String(80),nullable=False),sa.Column('is_demo',sa.Boolean(),nullable=False),sa.Column('stage',stage,nullable=False),sa.Column('score',sa.Integer()),sa.Column('classification',temperature),sa.Column('estimated_value',sa.Numeric(12,2),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    for name,cols in [('ix_leads_full_name',['full_name']),('ix_leads_email',['email']),('ix_leads_stage',['stage']),('ix_leads_classification',['classification']),('ix_leads_created_at',['created_at'])]: op.create_index(name,'leads',cols)
    op.create_table('lead_qualifications',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lead_id',sa.String(36),sa.ForeignKey('leads.id'),nullable=False),sa.Column('score',sa.Integer(),nullable=False),sa.Column('classification',temperature,nullable=False),sa.Column('intent',sa.String(80),nullable=False),sa.Column('fit',sa.String(80),nullable=False),sa.Column('urgency',sa.String(80),nullable=False),sa.Column('conversion_likelihood',sa.Integer(),nullable=False),sa.Column('summary',sa.Text(),nullable=False),sa.Column('needs',sa.JSON(),nullable=False),sa.Column('objections',sa.JSON(),nullable=False),sa.Column('recommended_action',sa.Text(),nullable=False),sa.Column('follow_up',sa.Text(),nullable=False),sa.Column('model',sa.String(80),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('lead_id'))
    op.create_index('ix_lead_qualifications_lead_id','lead_qualifications',['lead_id'],unique=True)
    op.create_table('lead_activities',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lead_id',sa.String(36),sa.ForeignKey('leads.id'),nullable=False),sa.Column('type',sa.String(80),nullable=False),sa.Column('title',sa.String(180),nullable=False),sa.Column('description',sa.Text()),sa.Column('metadata',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False));op.create_index('ix_lead_activities_lead_id','lead_activities',['lead_id']);op.create_index('ix_lead_activities_type','lead_activities',['type']);op.create_index('ix_lead_activities_created_at','lead_activities',['created_at'])
    op.create_table('notes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lead_id',sa.String(36),sa.ForeignKey('leads.id'),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False));op.create_index('ix_notes_lead_id','notes',['lead_id'])
    op.create_table('emails',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lead_id',sa.String(36),sa.ForeignKey('leads.id'),nullable=False),sa.Column('provider_id',sa.String(160)),sa.Column('subject',sa.String(255),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('sent_at',sa.DateTime(timezone=True)));op.create_index('ix_emails_lead_id','emails',['lead_id'])
    op.create_table('appointments',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lead_id',sa.String(36),sa.ForeignKey('leads.id'),nullable=False),sa.Column('external_id',sa.String(180),nullable=False),sa.Column('starts_at',sa.DateTime(timezone=True),nullable=False),sa.Column('ends_at',sa.DateTime(timezone=True)),sa.Column('status',sa.String(40),nullable=False),sa.Column('booking_url',sa.Text()),sa.UniqueConstraint('external_id',name='uq_appointment_external_id'));op.create_index('ix_appointments_lead_id','appointments',['lead_id'])
    op.create_table('automation_runs',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lead_id',sa.String(36),sa.ForeignKey('leads.id')),sa.Column('workflow',sa.String(120),nullable=False),sa.Column('status',runstatus,nullable=False),sa.Column('idempotency_key',sa.String(180),nullable=False),sa.Column('error',sa.Text()),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('idempotency_key',name='uq_automation_idempotency'));op.create_index('ix_automation_runs_lead_id','automation_runs',['lead_id']);op.create_index('ix_automation_runs_workflow','automation_runs',['workflow'])
def downgrade():
    for table in ['automation_runs','appointments','emails','notes','lead_activities','lead_qualifications','leads','users']: op.drop_table(table)
    op.execute('DROP TYPE IF EXISTS runstatus');op.execute('DROP TYPE IF EXISTS temperature');op.execute('DROP TYPE IF EXISTS stage')
